version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: wealthpulse-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wealthpulse
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    image: nethra0303/wealthpulse-backend:latest
    container_name: wealthpulse-backend
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/wealthpulse
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"

  frontend:
    image: nethra0303/wealthpulse-frontend:latest
    build:
      context: ./Frontend
      args:
        VITE_API_BASE_URL:  "http://3.238.245.228:8080"
        VITE_API_URL: "http://3.238.245.228:8080"
    container_name: wealthpulse-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql_data: